### ISSUE TITLE
update usginmodels.validate_file to add option to insert dummy data row

### ISSUE THREAD

**Issue by smrazgs** [usgin/usginmodels#5]
add a 'dummydata' Boolean, optional parameter to validate_file call. Default is false. If parameter is True, then insert a row of data as the first row in the CSV that contains dummy data values conforming to the xsd for the contentModel. This is necessary for files being sent by CKAN to PostGIS to deploy GeoServer WMS/WFS services, so that the data types inferred for the PostGres tables are correct and the resulting WFS responses will validate. 

Once this is resolved, we can test CKAN geoserver service deployment and open new issues there if necessary.
@usgin/usginmodels-update

**Comment by ccaudill** [comment]
@ykhadilkar-rei @dan-olaru-reisys @FuhuXia

**Comment by jessica-azgs** [comment]
@smrazgs Remember that several applications besides NGDS CKAN use usginmodels so any changes to existing methods would potentially break the other applications if they are ever updated or rebuilt.

**Comment by smrazgs** [comment]
@jessica-azgs I'm thinking if the new parameter in calls is optional, and the default is 'false' (don't add a dummy layer), it shouldn't break existing apps.  What do you think?

**Comment by jessica-azgs** [comment]
@smrazgs It shouldn't break existing apps in that case but just wanted to make sure everyone remembers/is aware that not just NGDS CKAN uses usginmodels.

**Comment by dan-olaru-reisys** [comment]
this should be fixed:

http://uat-ngds.reisys.com/dataset/tier3-borehole2

**Comment by FuhuXia** [comment]
code change checked in. verification in progress.
https://github.com/REI-Systems/usginmodels/commit/051b5dce515492716c2244d57df45e79c48444a0

**Comment by ccaudill** [comment]
Could you let me know when/where I can test to see if a CKAN-published file validates?

**Comment by dan-olaru-reisys** [comment]
http://uat-ngds.reisys.com/dataset/tier3-borehole2
http://uat-ngds.reisys.com/dataset/tier3-welllog2

let me know if you need anything else to try this.

**Comment by ccaudill** [comment]
Validated using XML spy! I think we can finally close out this issue. This is huge for us moving forward. Let me know if you find out why it is getting an exception error at http://schemas.usgin.org/validate/wfs
